// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PostModuleScssNamespace {
    export interface IPostModuleScss {
        date: string;
        header: string;
        image: string;
        post: string;
        preview: string;
        title: string;
    }
}

declare const PostModuleScssModule: PostModuleScssNamespace.IPostModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PostModuleScssNamespace.IPostModuleScss;
};

export = PostModuleScssModule;
