// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AuthorModuleScssNamespace {
  export interface IAuthorModuleScss {
    item: string
    name: string
  }
}

declare const AuthorModuleScssModule: AuthorModuleScssNamespace.IAuthorModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AuthorModuleScssNamespace.IAuthorModuleScss
}

export = AuthorModuleScssModule
