// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace HeaderModuleScssNamespace {
    export interface IHeaderModuleScss {
        title: string;
    }
}

declare const HeaderModuleScssModule: HeaderModuleScssNamespace.IHeaderModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: HeaderModuleScssNamespace.IHeaderModuleScss;
};

export = HeaderModuleScssModule;
